# This is a basic workflow to help you get started with Actions

name: Automated Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Python Markdown Documentation
        # You may pin to the exact commit or the version
        uses: CIBS-Okstate/Automated-Documentation@v1.0      #this is calls the action by a specific version version
        #uses: CIBS-Okstate/Automated-Documentation@a8d..... this is the most recent commit made in CIBS Automatic Documentation Documentation repository
        with:
          # Path to the source folder containing python code
          src_path: ./SimpleCmpressorModel/SimpleCompressorModel   #controls what and where to place the documentation
          #Directory to create markdown documents in
          # dst_path: ./SimpleCompressorModel/Docs
      - name: Open docs update PR
        uses: peter-evans/create-pull-request@v3      #utilizes a custom action to create a pull request with the updates to the documentation
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      
